[package]
authors = ["Walther Chen <walther.chen@gmail.com>"]
edition = "2018"
name = "roots"
version = "0.1.0"

[dependencies]
na = "0.18.1"
num = "0.2.0"

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "bench_roots"
harness = false
